In [1]:
pwd

'C:\\Users\\USER\\Desktop\\Data-Analysis\\5. Deep Learning'

In [2]:
# !conda install tensorflow

In [3]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
import tensorflow as tf

In [4]:
# seed 값 생성 (랜덤하지 않게 !)
seed = 0
numpy.random.seed(seed)
tf.random.set_seed(seed)    # tensorflow 1.15버전은 tf.set_random_seed(seed)

In [5]:
# 데이터 로드
dataset = numpy.loadtxt("./data/pima-indians-diabetes.csv", delimiter=",")
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [6]:
X = dataset[:,0:8]  # 컬럼 0~7까지를 feature로 한다.
Y = dataset[:,8]    # 컬럼 8을 class로 한다.

In [7]:
print(X.shape)
X

(768, 8)


array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
print(Y.shape)
Y

(768,)


array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [15]:
# 모델의 설정
model = Sequential()     #바구니
model.add(Dense(16, input_dim=8, activation='relu')) #층
model.add(Dense(8, activation='relu')) #층
model.add(Dense(1, activation='sigmoid')) #층

In [16]:
# 모델 컴파일    #이진분석                                     #정확도
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
# 모델 실행
model.fit(X, Y, epochs=200, batch_size=10)

Epoch 1/200
77/77 [==============================] - 0s 569us/step - loss: 0.3699 - accuracy: 0.8281
Epoch 2/200
77/77 [==============================] - 0s 440us/step - loss: 0.3718 - accuracy: 0.8333
Epoch 3/200
77/77 [==============================] - 0s 402us/step - loss: 0.3705 - accuracy: 0.8294
Epoch 4/200
77/77 [==============================] - 0s 414us/step - loss: 0.3683 - accuracy: 0.8372
Epoch 5/200
77/77 [==============================] - 0s 427us/step - loss: 0.3612 - accuracy: 0.8398
Epoch 6/200
77/77 [==============================] - 0s 440us/step - loss: 0.3554 - accuracy: 0.8372
Epoch 7/200
77/77 [==============================] - 0s 427us/step - loss: 0.3628 - accuracy: 0.8424
Epoch 8/200
77/77 [==============================] - 0s 440us/step - loss: 0.3611 - accuracy: 0.8464
Epoch 9/200
77/77 [==============================] - 0s 427us/step - loss: 0.3582 - accuracy: 0.8438
Epoch 10/200
77/77 [==============================] - 0s 427us/step - loss: 0.3643 - accura

77/77 [==============================] - 0s 414us/step - loss: 0.3562 - accuracy: 0.8385
Epoch 82/200
77/77 [==============================] - 0s 389us/step - loss: 0.3569 - accuracy: 0.8385
Epoch 83/200
77/77 [==============================] - 0s 402us/step - loss: 0.3623 - accuracy: 0.8438
Epoch 84/200
77/77 [==============================] - 0s 427us/step - loss: 0.3698 - accuracy: 0.8255
Epoch 85/200
77/77 [==============================] - 0s 440us/step - loss: 0.3673 - accuracy: 0.8411
Epoch 86/200
77/77 [==============================] - 0s 402us/step - loss: 0.3628 - accuracy: 0.8464
Epoch 87/200
77/77 [==============================] - 0s 376us/step - loss: 0.3576 - accuracy: 0.8424
Epoch 88/200
77/77 [==============================] - 0s 440us/step - loss: 0.3586 - accuracy: 0.8503
Epoch 89/200
77/77 [==============================] - 0s 402us/step - loss: 0.3615 - accuracy: 0.8490
Epoch 90/200
77/77 [==============================] - 0s 402us/step - loss: 0.3511 - accuracy: 

77/77 [==============================] - 0s 440us/step - loss: 0.3573 - accuracy: 0.8346
Epoch 161/200
77/77 [==============================] - 0s 414us/step - loss: 0.3583 - accuracy: 0.8359
Epoch 162/200
77/77 [==============================] - 0s 402us/step - loss: 0.3495 - accuracy: 0.8568
Epoch 163/200
77/77 [==============================] - 0s 389us/step - loss: 0.3554 - accuracy: 0.8424
Epoch 164/200
77/77 [==============================] - 0s 414us/step - loss: 0.3503 - accuracy: 0.8320
Epoch 165/200
77/77 [==============================] - 0s 427us/step - loss: 0.3518 - accuracy: 0.8503
Epoch 166/200
77/77 [==============================] - 0s 389us/step - loss: 0.3621 - accuracy: 0.8411
Epoch 167/200
77/77 [==============================] - 0s 389us/step - loss: 0.3569 - accuracy: 0.8424
Epoch 168/200
77/77 [==============================] - 0s 414us/step - loss: 0.3550 - accuracy: 0.8372
Epoch 169/200
77/77 [==============================] - 0s 427us/step - loss: 0.3608 - a

In [30]:
# 결과 출력
print("\n Accuracy: %.4f" % (model.evaluate(X, Y)[1]))

24/24 [==============================] - 0s 498us/step - loss: 0.3926 - accuracy: 0.8203

 Accuracy: 0.8203
